
use Lingua::Romana::Perligata;

LISTIS CONSCRIBEMENTA V TUM X DA.

XO LISTA ADMETAMENTUM DA.
XUM POSTINCRESCEMENTUM.
XO EGRESSO SCRIBE.

PER QUISQUE IN LISTIS FAC
SIC
    HOC COMEMENTUM TUM NOVUMVERSUM EGRESSO SCRIBE.
CIS

