
use Lingua::Romana::Perligata;

VOLVERE SIC
    DEXTRO CXVI CONICEMENTUM DA.
    ALEO DEXTRUM TUM II RECIDEMENTUM TUM I ADDEMENTUM DA.

    DICTUM SIC ALEA JACTA EST CIS TUM BIGUTTAM TUM STADIUM TUM CUM ALEUM COMEMENTUM TUM NOVUMVERSUM EGRESSO SCRIBE.
CIS

MEIS COACERVATIS SIC I TUM III TUM V CIS DAMENTUM.

VOLVE.
VOLVE.
VOLVE.
VOLVE.
VOLVE.
VOLVE.
VOLVE.
VOLVE.
VOLVE.
VOLVE.

