
use Lingua::Romana::Perligata;

VOLVERE SIC
    DEXTRO CXVI CONICEMENTUM DA.
    ALEO DEXTRUM TUM II RECIDEMENTUM TUM I ADDEMENTUM DA.

    DICTUM SIC ALEA JACTA EST CIS TUM BIGUTTAM TUM STADIUM TUM CUM ALEUM COMEMENTUM TUM NOVUMVERSUM EGRESSO SCRIBE.
    ALEUM REDDE
CIS

AO DA VOLVEMENTUM.
VOLVE.
VOLVE.
VOLVE.
VOLVE.
VOLVE.
VOLVE.
VOLVE.
VOLVE.
VOLVE.


DICTUM SIC AO CIS TUM CUM AUM COMEMENTUM TUM NOVUMVERSUM EGRESSO SCRIBE.

BIS I TUM X CONSCRIBEMENTA DA.

DA MO BA ADMETAMENTUM.
MO POSTINCRESCE.

MUM COMEMENTUM TUM NOVUMVERSUM EGRESSO SCRIBE.

DA FO CXVI.
MIMUM BORUM DA FUM.
DA ZO MIMUM BORUM.

ZUM COMEMENTUM TUM NOVUMVERSUM EGRESSO SCRIBE.


