
use Lingua::Romana::Perligata;

DEXTRO CXVI CONICEMENTUM DA.
ALEO DEXTRUM TUM IV RECIDEMENTUM DA.

DICTUM SIC ALEA IACTA EST CIS TUM BIGUTTAM TUM STADIUM TUM CUM ALEUM COMEMENTUM TUM NOVUMVERSUM EGRESSO SCRIBE.



