
use Lingua::Romana::Perligata;

DOMUS TABULA.

MEIS DATIS.

    NEWERE
    SIC
        MEIS DATIBUS.
        COUNTO INTRA TABULA POSTINCRESCE.
        PREINCRESCEMENTO NO INTRA MAX DATORUM
        INTRA TABULA INTRA MAX DA I.
            REDDE DATIBUS NULLIUM HORUM BENEDICTUM.
        CIS
    CIS

    PRINTERE
    SIC
        MEO SELFO HIS DECAPITAMENTUM DA.
        MODUS TUM INDEFINITUS TUM HAEC INQUEMENTUM CARPE.
    CIS

    DOMUS PRINCEPS.

    MEO OBJECTO DA NEWERMENTUM APUD TABULA.

    I TUM III PRINTE APUD OBJECTUM.
    I PRINTE APUD OBJECTUM.

ET TUM CETERA INQUEMENTUM PRINTE APUD TABULA.
