
use Lingua::Romana::Perligata
# 'converte'
;

ADNOTA MENDA PYTHAGORICA AD CENTUM

PER QUISQUE SINISTRUM IN I TUM X CONSCRIBEMENTO FAC SIC
PER QUISQUE DEXTRUM IN I TUM X CONSCRIBEMENTO FAC SIC SINISTRUM
TUM DEXTRUM MULTIPLICAMENTUM COMEMENTUM TUM STADIUM EGRESSO
SCRIBE. CIS NOVUMVERSUM EGRESSO SCRIBE. CIS.

