use Lingua::Romana::Perligata;

ADNOTA PLUSMINUSQUE LUDO.

MEO MAXIMO C DA.    DICTUM SIC MAXIMUM CIS
TUM  BIGUTTAM  TUM   LACUNAM  TUM  MAXIMUM
EGRESSO  SCRIBE.  MAXIMUM  COMEMENTUM  TUM 
NOVUMVERSUM  EGRESSO  SCRIBE.  MEO  SCOPIO 
DA  C  CONICEMENTUM  DECOLLAMENTUM.    MEO 
DIVINO DA I.   NOVUMVERSUM EGRESSO SCRIBE.

DUM  SCOPIUM  TUM  DIVINUM  NON AEQUALITAM
FAC SIC DA DIVINO VESTIBULO PERLEGEMENTUM.
SI  SCOPIUM  TUM  DIVINUM PRAESTANTIAM FAC
SIC  DICTUM  SIC  EST  MAGNA NIMIS CIS TUM 
NOVUMVERSUM   EGRESSO   SCRIBE.   CIS   SI 
DIVINUM  TUM  SCOPIUM PRAESTANTIAM FAC SIC
DICTUM   SIC   EST    ANGUSTUS   CIS   TUM 
NOVUMVERSUM   EGRESSO   SCRIBE.  CIS   CIS 
SCOPIUM    COMEMENTUM    EGRESSO   SCRIBE.
NOVUMVERSUM         EGRESSO        SCRIBE.

