
use Lingua::Romana::Perligata;

ADNOTA RELIQUA CALCULO.

DICTUM SIC VESTIBULA PRIMO: CIS TUM LACUNA EGRESSO SCRIBE.
AO VESTIBULO PERLEGEMENTUM DA.
DICTUM SIC VESTIBULA SECUNDO: CIS TUM LACUNA EGRESSO SCRIBE.
BO VESTIBULO PERLEGEMENTUM DA.
BO V DA.
DICTUM SIC RELIQUA CIS TUM LACUNAM TUM CUM AUM TUM BUM RECIDEMENTUM TUM NOVUMVERSUM EGRESSO SCRIBE.

